name: coverage

on:
  push:
    branches: [ master ]

permissions:
  contents: read

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: pdo_mysql, redis
          coverage: pcov

      - name: Cache Composer dependencies
        uses: actions/cache@v6
        with:
          path: ~/.composer/cache
          key: php-8.1-composer-locked-${{ hashFiles('composer.lock') }}
          restore-keys: php-8.1-composer-locked-

      - name: Install Composer
        uses: ramsey/composer-install@v4
        with:
          dependency-versions: highest

      - name: Tests
        run: vendor/bin/phpunit --testsuite=unit --coverage-clover=coverage.xml

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v7
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: false
